baseURL = 'https://ai-independence.com/'
languageCode = 'en-us'
title = 'AI Independence'
theme = 'terminal'

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 6
  fullWidthTheme = false
  centerTheme = true
  autoCursor = true
  
  # AI Independence specific settings
  subtitle = "Escape AI surveillance and reclaim your digital sovereignty"
  keywords = ["ai independence", "digital privacy", "surveillance countermeasures", "local ai", "privacy tools"]
  
  # Conversion optimization
  enableEmailCapture = true
  privacyFocused = true
  
[params.logo]
  logoText = "ai-free:~$"
  logoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "start"
    name = "start-here/"
    url = "/start-here/"
    weight = 5
  [[menu.main]]
    identifier = "privacy"
    name = "privacy/"
    url = "/categories/privacy/"
    weight = 10
  [[menu.main]]
    identifier = "surveillance"
    name = "surveillance/"
    url = "/categories/surveillance/"
    weight = 20
  [[menu.main]]
    identifier = "local-ai"
    name = "local-ai/"
    url = "/categories/local-ai/"
    weight = 30
  [[menu.main]]
    identifier = "tools"
    name = "tools/"
    url = "/categories/tools/"
    weight = 40
  [[menu.main]]
    identifier = "free-kit"
    name = "free-kit/"
    url = "/ai-surveillance-escape-kit/"
    weight = 45
  [[menu.main]]
    identifier = "about"
    name = "about.txt"
    url = "/about/"
    weight = 50
